version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/postgres
    env_file:
      - .env

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    restart: on-failure
