version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/postgres
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    volumes:
       - .:/code:z
    env_file:
      - .env
    depends_on:
      - db
