# Generated by Django 5.0.6 on 2024-07-22 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signups', '0003_alter_touristsignup_payment'),
        ('tours', '0004_alter_tour_locations_alter_tourinstance_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloTourInstanceMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('trello_id', models.CharField(max_length=30, verbose_name='Trello ID')),
                ('trello_data', models.JSONField(verbose_name='Данные в Trello')),
                ('tour_instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trello_integration', to='tours.tourinstance', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Тур в Trello',
                'verbose_name_plural': 'Туры в Trello',
            },
        ),
        migrations.CreateModel(
            name='TrelloTouristSignupMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('trello_id', models.CharField(max_length=30, verbose_name='Trello ID')),
                ('trello_data', models.JSONField(verbose_name='Данные в Trello')),
                ('tourist_signup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trello_integration', to='signups.touristsignup', verbose_name='Запись на тур')),
            ],
            options={
                'verbose_name': 'Запись на тур в Trello',
                'verbose_name_plural': 'Записи на тур в Trello',
            },
        ),
    ]
