# Generated by Django 5.0.6 on 2024-06-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('manually', 'Вручную'), ('telegram', 'Telegram')], max_length=255, verbose_name='Канал оплаты')),
                ('info', models.JSONField(verbose_name='Информация')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
