# Generated by Django 5.0.6 on 2024-06-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reserved', 'Забронировано'), ('payed', 'Оплачено')], default='reserved', max_length=255, verbose_name='Статус')),
                ('people_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество людей')),
                ('reserved_till', models.DateTimeField(blank=True, null=True, verbose_name='Бронь до')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourist_signups', to='payments.payment')),
                ('tour_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourist_signups', to='tours.tourinstance')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourist_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись на тур',
                'verbose_name_plural': 'Записи на тур',
            },
        ),
    ]
