# Generated by Django 5.0.6 on 2024-07-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_created_date_and_more'),
        ('signups', '0002_alter_touristsignup_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristsignup',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tourist_signup', to='payments.payment'),
        ),
    ]
