# Generated by Django 5.0.6 on 2024-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tourinstance_options_alter_tour_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='locations',
            field=models.ManyToManyField(related_name='tours', through='tours.TourLocation', to='tours.location', verbose_name='Локации'),
        ),
        migrations.AlterField(
            model_name='tourinstance',
            name='guides',
            field=models.ManyToManyField(related_name='tour_instances', to='tours.guide', verbose_name='Гиды'),
        ),
    ]
