from decouple import config


TELEGRAM_TOKEN = config("TELEGRAM_TOKEN")
TELEGRAM_PAYMENTS_TOKEN = config("TELEGRAM_PAYMENTS_TOKEN")

TRELLO_BASE_URL = config("TRELLO_BASE_URL")
TRELLO_API_KEY = config("TRELLO_API_KEY")
TRELLO_TOKEN = config("TRELLO_TOKEN")
TRELLO_BOARD_ID = config("TRELLO_BOARD_ID")
